### ISSUE TITLE
The presenter console isn't properly documented

### ISSUE THREAD

**Issue by regebro** [regebro/hovercraft#117]

**Comment by neithere** [comment]
+1, I've used it for rehearsing, but I don't understand if there's a sensible way to use it during actual presentation.

**Comment by regebro** [comment]
I use two browser windows and drag one to the external screen (hooked up to the projector) and leave one on the main laptop screen, then I fullscreen (F11) both of them.

**Comment by joshuacox** [comment]
ya there needs  to be a section in the docs on presentation mode. +1

**Comment by yeyeto2788** [comment]
@mkohler as far as I know you can do it from both windows.
![Screenshot from 2019-11-05 08-30-49](https://user-images.githubusercontent.com/6363686/68187324-b05c3e00-ffa6-11e9-97d2-a549a70c0882.png)

in the picture above you can see both windows as @regebro mentioned, and you can go to the next slide either from the presenter console or the presentation itself.

@regebro this issue seems to be incomplete at least on what the real issue is, can we have more info about what is the issue? from the title I can get some details but not exactly why this was reported.

Regards.

P.D: Do not take into consideration what it is written on the slides. hahahaha

**Comment by regebro** [comment]
The console simply follows what happens in the main window, and it also sends navigation commands to the main window. So I'm not sure what mkohlers question, really is.

**Comment by mkohler** [comment]
Ah...now I see how it works. I never noticed that pressing "P" was creating a second tab and switching focus to that tab. I had just been creating two tabs, opening the presentation in both, and pressing "P" in one of them.

I wrote up some presenter console docs and opened PR #206.

**Comment by ankostis** [comment]
(thank you for this excellent project)
It would be nice to document additionally that it's only the *presentation tab* which accepts command shortcuts (e.g. [G, 1]), and not the *console tab* (is that correct?).
