### ISSUE TITLE
Support request: How to add slides with fullscreen images

### ISSUE THREAD

**Issue by ccamara** [regebro/hovercraft#174]
I would like to know which is the best way to achieve slides/steps displaying a fullscreen image.

After playing a bit with raw impress.js I think the best way to do it is to add a class to the slide and theme it accordingly (You can see the results of my failed attempts at https://ccamara.github.io/impress-slides-sample/ -repo with the code [here](https://github.com/ccamara/impress-slides-sample)).

Unfortunately, although I know how to add a custom class to slides (#171 ), I haven't succeeded in my theming.

I realized that if I change step's width to a higher value, images are displayed fullscreen, but at the cost of overlapping one to the other (due to 1600 default's values for movement)

I am afraid it might be a css issue, but I am not good at all with positioning and styling objects.

**Comment by regebro** [comment]
I don't know if this will work, but have you tried using width="100%"?

**Comment by regebro** [comment]
Did you get anywhere with this?

**Comment by ccamara** [comment]
Unfortunately, not :(

**Comment by yeyeto2788** [comment]
Hey @ccamara, have you tried something like the example below using the data-scale and playing with the width and height?

```html
<div class="step" data-scale=2>
<img src="https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg" style="position: absolute; left: 0px; top: 0px; z-index: -1; width: 9000px; height: 1000px">
</div>
```

**Comment by regebro** [comment]
To explain: The principles of Hovercraft is that it creates a 3D Canvas and puts HTML objects on them, and then you can move around over those objects. So "fullscreen" doesn't exist per se. So you just have to fit the images to how big the screen is.

But that can change if you watch it on different sized screens, especially that many projectors use 4:3 instead of 19:6 for example. But better than that you probably won't get.
