### ISSUE TITLE
Missing docs or bug?

### ISSUE THREAD

**Issue by MichaelHierweck** [regebro/hovercraft#86]
When trying to include static image files from a css file as part of template hovercraft tries to copy those files to the target directory but fails because it constructs source file paths that include the template *file* name, such as: .../folder/template/mytemplate.cfg/img/picture.jpg

CSS ist something like: html {background: top center no-repeat url("../img/picture.jpg")}

I tried serveral variants of the url, even placing the picture in the css folder. I tried registering the file as resourse (resources = img/picture.jpg) in the configuration file, too.

I'm unsure whether this is a bug oder just missing documentation? (Can anyone provide an example?)

**Comment by penumbra-01** [comment]
I don't know if it's related but I had an issue with `resource`. In a custom template (using the `template.xsl` from `/simple`), I changed it to `resources` and know everything works. The error I had was actually coming for something parsing the CSS to ensure `url` tags actually points to something existing. So the doc might be wrong, dunno...

**Comment by penumbra-01** [comment]
Ok, I narrowed the bug to line 135 of `generate.py`:
```python
css_base = template_info.template if resource.is_in_template else sourcedir
```
First of all, it seems that you should not manually add resources to template when your css embed them using relative path, hovercraft handles it. The problem seems to be that `resource.is_in_template` is `True` while it should be `False`, that's why it uses `template_info.template` instead of `sourcedir` I think. Anyway, if you force that:
```python
css_base = sourcedir
```
Errors will be gone, but an other one might re-appears when using `resources` from template (which is probably used for image displayed within the presentation itself).

**Comment by regebro** [comment]
This should be solved now. The workaround until this fix is released is to not include the template.cfg when you give the template path.
