### ISSUE TITLE
presentation not automatically rebuilt when changed

### ISSUE THREAD

**Issue by FelixHaller** [regebro/hovercraft#98]
Hi,

I don't know if I'm doing something wrong, but there was no Q&A section, so I'm writing a ticket.

I started the built-in python web server with 
`$ hovercraft presentation.rst`
but when I make changes in presentation.rst then save the file and reload the webpage I get the same page as before.

I'm on Arch Linux with python 3.5 and latest hovercraft (via pip3)

Thank you in advance
Greets
Felix

**Comment by regebro** [comment]
No, you aren't doing anything wrong. I have noticed that in some cases when the rebuild fails, it will stop rebuilding, and then stopping and restarting should get that fixed. I haven't had time to investigate that more closely. But if you don't get any error messages that's not the reason.

**Comment by FelixHaller** [comment]
Nope. I don't get any error message. As I described - nothing happens.

**Comment by regebro** [comment]
Is this on a local disk or a network disk? What filesystem is it?

**Comment by FelixHaller** [comment]
It's a local disk formatted ext4. But i found out something more interesting. When I edit the file with vim the presentation is rebuild as wanted, but not with geany or gedit (I only tested these two).

**Comment by regebro** [comment]
Interesting indeed. I'll see what I can find.

**Comment by regebro** [comment]
I can confirm that indeed, with gedit it doesn't get updated. If this is a bug in gedit or in the library (watchdog) I'm using to watch files, I don't know.

**Comment by lukhar** [comment]
The problem lies in `HovercraftEventHandler` class:
```python
...
def on_modified(self, event):
    if event.src_path in self.filelist:
        print("File %s modified, update presentation" % event.src_path)
        self.quit = True
```

From `watchdog` perspective some editors (like vim) when saving changes to the file actually delete the old instance replacing it with the new one (with modifications). So technically they create a new file every time you save your changes. That is why `on_modified` method doesn't pick up the change made by vim (or gedit). The fix that worked for me (locally) is:
```python
...
    def on_modified(self, event):
        self._update(event.src_path)

    def on_created(self, event):
        self._update(event.src_path)

    def _update(self, src_path):
        if src_path in self.filelist:
            print("File %s modified, update presentation" % src_path)
            self.quit = True
```
I'll follow up with the pull soon. Let me know what you guys think.

**Comment by regebro** [comment]
Ah, OK. That's not what your patch did, just FYI, both methods was called on_modified.

**Comment by lukhar** [comment]
Yeah sorry about that, I've updated PR with intended changes now.

**Comment by regebro** [comment]
on_created isn't called, on_moved is, however, so I added that. That fixes the issue. With vi/vim you now get multiple updates, but that's a better problem. :-)

**Comment by lukhar** [comment]
I've updated hovercraft to latest version and since the fix worked only on my Linux box (on OSX the presentation is still not being updated) I did some more digging. Here's what I found:
* `on_created` is called on both platforms when modifying file with **vim** 
* `on_moved` is called only on Linux platform when  modifying file with **vim** but it's not called on OSX
* `on_created` doesn't work when you modify file with **gedit** on Linux

My guess is it has to do with how different file systems interpret file changes made by editors. I've created PR which fixes that particular issue for vim on OSX here: https://github.com/regebro/hovercraft/pull/120

**Comment by regebro** [comment]
Hm. I'll add on_created as well then, but I think I need a better way of handling this as it means that with vim on Linux it'll rebuild three times. :-)

**Comment by regebro** [comment]
It only gets rebuilt once, so it's fine. Commited, will be a part of next release.
